stages:
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    params:
    - data_preprocessing.test_size
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    outs:
    - data/interim
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/interim
    - src/model/model_building.py
    params:
    - model_building.colsample_bytree
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    - model_building.subsample 
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - data/interim
    - models/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - metrics.json
